#!/usr/bin/env python3
"""
Read eqdata binary file (Fortran unformatted) and export to CSV files.

This script reads the binary equilibrium data file generated by the TASK/EQ code
(specifically the EQSAVE subroutine in eqfile.f) and exports all data to CSV format.

Usage:
    python read_eqdata_to_csv.py [eqdata_file] [output_prefix]
    
Examples:
    python read_eqdata_to_csv.py eqdata eq_output
    python read_eqdata_to_csv.py  # Uses default: eqdata -> eqdata_*

Author: Generated based on analysis of TASK/EQ Fortran source code
"""

import sys
import os
import struct
import numpy as np


def read_fortran_record(f):
    """
    Read a single Fortran unformatted record.
    
    Fortran sequential unformatted files have a 4-byte record length marker
    before and after each record.
    
    Returns the raw bytes of the record data.
    """
    # Read leading record length (4 bytes, little-endian int32)
    marker = f.read(4)
    if len(marker) == 0:
        return None  # EOF
    if len(marker) < 4:
        raise IOError(f"Incomplete record marker: got {len(marker)} bytes")
    
    record_len = struct.unpack('<i', marker)[0]
    
    # Read the record data
    data = f.read(record_len)
    if len(data) < record_len:
        raise IOError(f"Incomplete record data: expected {record_len}, got {len(data)}")
    
    # Read trailing record length marker
    trailing = f.read(4)
    if len(trailing) < 4:
        raise IOError("Incomplete trailing record marker")
    
    trailing_len = struct.unpack('<i', trailing)[0]
    if trailing_len != record_len:
        raise IOError(f"Record length mismatch: {record_len} vs {trailing_len}")
    
    return data


def read_eqdata(filename):
    """
    Read the eqdata binary file and return all data in a dictionary.
    
    The file format is Fortran unformatted sequential, with the following records:
    1. RR, BB, RIP (3 floats)
    2. NRGMAX, NZGMAX (2 ints)
    3. RG(1:NRGMAX)
    4. ZG(1:NZGMAX)
    5. PSIRZ(1:NRGMAX, 1:NZGMAX)
    6. NPSMAX (1 int)
    7-11. PSIPS, PPPS, TTPS, TEPS, OMPS (each NPSMAX floats)
    12. 8 integers: NSGMAX, NTGMAX, NUGMAX, NRMAX, NTHMAX, NSUMAX, NRVMAX, NTVMAX
    13-15. PSI, DELPSI, HJT (each NSGMAX x NTGMAX, but written as NSG varies fastest)
    16. RAXIS, ZAXIS, PSITA, PSIPA, PSI0 (5 floats)
    17-21. PSIPNV, PSIPV, PSITV, QPV, TTV (each NRVMAX floats)
    22. RA, RKAP, RDLT, RB, FRBIN (5 floats)
    23-27. Profile parameters (6,6,6,6,3 floats)
    28. HJTRZ(1:NRGMAX, 1:NZGMAX)
    """
    
    data = {}
    
    with open(filename, 'rb') as f:
        # Record 1: RR, BB, RIP
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['RR'] = vals[0]  # Major radius [m]
        data['BB'] = vals[1]  # Toroidal magnetic field [T]
        data['RIP'] = vals[2]  # Plasma current [A]
        
        # Record 2: NRGMAX, NZGMAX
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.int32)
        data['NRGMAX'] = vals[0]
        data['NZGMAX'] = vals[1]
        NRGMAX = data['NRGMAX']
        NZGMAX = data['NZGMAX']
        
        # Record 3: RG(1:NRGMAX) - R grid coordinates
        rec = read_fortran_record(f)
        data['RG'] = np.frombuffer(rec, dtype=np.float64)
        
        # Record 4: ZG(1:NZGMAX) - Z grid coordinates
        rec = read_fortran_record(f)
        data['ZG'] = np.frombuffer(rec, dtype=np.float64)
        
        # Record 5: PSIRZ(1:NRGMAX, 1:NZGMAX) - Poloidal flux on (R,Z) grid
        # Fortran stores column-major, so we reshape accordingly
        rec = read_fortran_record(f)
        psirz_flat = np.frombuffer(rec, dtype=np.float64)
        data['PSIRZ'] = psirz_flat.reshape((NRGMAX, NZGMAX), order='F')
        
        # Record 6: NPSMAX
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.int32)
        data['NPSMAX'] = vals[0]
        NPSMAX = data['NPSMAX']
        
        # Records 7-11: 1D profile arrays on psi grid
        rec = read_fortran_record(f)
        data['PSIPS'] = np.frombuffer(rec, dtype=np.float64)  # Normalized psi
        
        rec = read_fortran_record(f)
        data['PPPS'] = np.frombuffer(rec, dtype=np.float64)   # Pressure profile
        
        rec = read_fortran_record(f)
        data['TTPS'] = np.frombuffer(rec, dtype=np.float64)   # TT profile (F)
        
        rec = read_fortran_record(f)
        data['TEPS'] = np.frombuffer(rec, dtype=np.float64)   # Temperature profile
        
        rec = read_fortran_record(f)
        data['OMPS'] = np.frombuffer(rec, dtype=np.float64)   # Omega profile
        
        # Record 12: 8 integers - dimension parameters
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.int32)
        data['NSGMAX'] = vals[0]
        data['NTGMAX'] = vals[1]
        data['NUGMAX'] = vals[2]
        data['NRMAX'] = vals[3]
        data['NTHMAX'] = vals[4]
        data['NSUMAX'] = vals[5]
        data['NRVMAX'] = vals[6]
        data['NTVMAX'] = vals[7]
        NSGMAX = data['NSGMAX']
        NTGMAX = data['NTGMAX']
        NRVMAX = data['NRVMAX']
        
        # Records 13-15: 2D arrays on (sigma, theta) mesh
        # These are written with NSG as the fastest varying index
        rec = read_fortran_record(f)
        psi_flat = np.frombuffer(rec, dtype=np.float64)
        data['PSI'] = psi_flat.reshape((NSGMAX, NTGMAX), order='F')
        
        rec = read_fortran_record(f)
        delpsi_flat = np.frombuffer(rec, dtype=np.float64)
        data['DELPSI'] = delpsi_flat.reshape((NSGMAX, NTGMAX), order='F')
        
        rec = read_fortran_record(f)
        hjt_flat = np.frombuffer(rec, dtype=np.float64)
        data['HJT'] = hjt_flat.reshape((NSGMAX, NTGMAX), order='F')
        
        # Record 16: Axis and boundary parameters
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['RAXIS'] = vals[0]   # R coordinate of magnetic axis
        data['ZAXIS'] = vals[1]   # Z coordinate of magnetic axis
        data['PSITA'] = vals[2]   # Toroidal flux at axis
        data['PSIPA'] = vals[3]   # Poloidal flux at axis
        data['PSI0'] = vals[4]    # Poloidal flux normalization
        
        # Records 17-21: Radial profile arrays (NRVMAX elements each)
        rec = read_fortran_record(f)
        data['PSIPNV'] = np.frombuffer(rec, dtype=np.float64)  # Normalized poloidal flux
        
        rec = read_fortran_record(f)
        data['PSIPV'] = np.frombuffer(rec, dtype=np.float64)   # Poloidal flux
        
        rec = read_fortran_record(f)
        data['PSITV'] = np.frombuffer(rec, dtype=np.float64)   # Toroidal flux
        
        rec = read_fortran_record(f)
        data['QPV'] = np.frombuffer(rec, dtype=np.float64)     # Safety factor
        
        rec = read_fortran_record(f)
        data['TTV'] = np.frombuffer(rec, dtype=np.float64)     # F = R*Bt
        
        # Record 22: Geometry parameters
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['RA'] = vals[0]      # Minor radius
        data['RKAP'] = vals[1]    # Elongation (kappa)
        data['RDLT'] = vals[2]    # Triangularity (delta)
        data['RB'] = vals[3]      # Outer boundary radius
        data['FRBIN'] = vals[4]   # Inner fraction
        
        # Records 23-27: Profile parameters
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['PJ0'] = vals[0]
        data['PJ1'] = vals[1]
        data['PJ2'] = vals[2]
        data['PROFJ0'] = vals[3]
        data['PROFJ1'] = vals[4]
        data['PROFJ2'] = vals[5]
        
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['PP0'] = vals[0]
        data['PP1'] = vals[1]
        data['PP2'] = vals[2]
        data['PROFP0'] = vals[3]
        data['PROFP1'] = vals[4]
        data['PROFP2'] = vals[5]
        
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['PT0'] = vals[0]
        data['PT1'] = vals[1]
        data['PT2'] = vals[2]
        data['PROFTP0'] = vals[3]
        data['PROFTP1'] = vals[4]
        data['PROFTP2'] = vals[5]
        
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['PV0'] = vals[0]
        data['PV1'] = vals[1]
        data['PV2'] = vals[2]
        data['PROFV0'] = vals[3]
        data['PROFV1'] = vals[4]
        data['PROFV2'] = vals[5]
        
        rec = read_fortran_record(f)
        vals = np.frombuffer(rec, dtype=np.float64)
        data['PROFR0'] = vals[0]
        data['PROFR1'] = vals[1]
        data['PROFR2'] = vals[2]
        
        # Record 28: HJTRZ(1:NRGMAX, 1:NZGMAX) - Current density on (R,Z) grid
        try:
            rec = read_fortran_record(f)
            if rec:
                hjtrz_flat = np.frombuffer(rec, dtype=np.float64)
                data['HJTRZ'] = hjtrz_flat.reshape((NRGMAX, NZGMAX), order='F')
            else:
                data['HJTRZ'] = np.zeros((NRGMAX, NZGMAX))
        except Exception:
            # HJTRZ may not exist in older files
            data['HJTRZ'] = np.zeros((NRGMAX, NZGMAX))
            print("Warning: Could not read HJTRZ array, using zeros")
    
    return data


def export_to_csv(data, prefix):
    """
    Export data dictionary to CSV files.
    Uses only numpy without pandas for broader compatibility.
    """
    output_files = []
    
    # 1. Scalar parameters
    param_names = [
        'RR', 'BB', 'RIP',
        'NRGMAX', 'NZGMAX', 'NPSMAX',
        'NSGMAX', 'NTGMAX', 'NUGMAX', 'NRMAX', 'NTHMAX', 'NSUMAX', 'NRVMAX', 'NTVMAX',
        'RAXIS', 'ZAXIS', 'PSITA', 'PSIPA', 'PSI0',
        'RA', 'RKAP', 'RDLT', 'RB', 'FRBIN',
        'PJ0', 'PJ1', 'PJ2', 'PROFJ0', 'PROFJ1', 'PROFJ2',
        'PP0', 'PP1', 'PP2', 'PROFP0', 'PROFP1', 'PROFP2',
        'PT0', 'PT1', 'PT2', 'PROFTP0', 'PROFTP1', 'PROFTP2',
        'PV0', 'PV1', 'PV2', 'PROFV0', 'PROFV1', 'PROFV2',
        'PROFR0', 'PROFR1', 'PROFR2'
    ]
    param_descriptions = [
        'Major radius [m]', 'Toroidal field [T]', 'Plasma current [A]',
        'R grid points', 'Z grid points', 'Psi profile points',
        'Sigma mesh points', 'Theta mesh points', 'NU points', 'Radial points',
        'Theta flux points', 'Surface points', 'Radial volume points', 'Theta volume points',
        'R of magnetic axis [m]', 'Z of magnetic axis [m]',
        'Toroidal flux at axis', 'Poloidal flux at axis', 'Flux normalization',
        'Minor radius [m]', 'Elongation', 'Triangularity', 'Outer radius [m]', 'Inner fraction',
        'J profile P0', 'J profile P1', 'J profile P2', 'J PROF0', 'J PROF1', 'J PROF2',
        'P profile P0', 'P profile P1', 'P profile P2', 'P PROF0', 'P PROF1', 'P PROF2',
        'T profile P0', 'T profile P1', 'T profile P2', 'T PROF0', 'T PROF1', 'T PROF2',
        'V profile P0', 'V profile P1', 'V profile P2', 'V PROF0', 'V PROF1', 'V PROF2',
        'R PROF0', 'R PROF1', 'R PROF2'
    ]
    
    filename = f'{prefix}_parameters.csv'
    with open(filename, 'w') as f:
        f.write('Parameter,Value,Description\n')
        for name, desc in zip(param_names, param_descriptions):
            if name in data:
                val = data[name]
                if isinstance(val, (int, np.integer)):
                    f.write(f'{name},{val},{desc}\n')
                else:
                    f.write(f'{name},{val:.15e},{desc}\n')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    # 2. R grid
    filename = f'{prefix}_RG_grid.csv'
    with open(filename, 'w') as f:
        f.write('index,RG\n')
        for i, val in enumerate(data['RG']):
            f.write(f'{i},{val:.15e}\n')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    # 3. Z grid
    filename = f'{prefix}_ZG_grid.csv'
    with open(filename, 'w') as f:
        f.write('index,ZG\n')
        for i, val in enumerate(data['ZG']):
            f.write(f'{i},{val:.15e}\n')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    # 4. PSIRZ 2D array
    filename = f'{prefix}_PSIRZ.csv'
    np.savetxt(filename, data['PSIRZ'], delimiter=',', 
               header=','.join([f'Z_{i}' for i in range(data['NZGMAX'])]),
               comments='')
    output_files.append(filename)
    print(f"Saved: {filename} (shape: {data['NRGMAX']} x {data['NZGMAX']})")
    
    # 5. 1D profiles on psi grid
    filename = f'{prefix}_1D_profiles.csv'
    nps = data['NPSMAX']
    with open(filename, 'w') as f:
        f.write('index,PSIPS,PPPS,TTPS,TEPS,OMPS\n')
        for i in range(nps):
            f.write(f'{i},{data["PSIPS"][i]:.15e},{data["PPPS"][i]:.15e},'
                   f'{data["TTPS"][i]:.15e},{data["TEPS"][i]:.15e},{data["OMPS"][i]:.15e}\n')
    output_files.append(filename)
    print(f"Saved: {filename} ({nps} points)")
    
    # 6. PSI on (sigma, theta) mesh
    filename = f'{prefix}_PSI_mesh.csv'
    np.savetxt(filename, data['PSI'], delimiter=',',
               header=','.join([f'theta_{i}' for i in range(data['NTGMAX'])]),
               comments='')
    output_files.append(filename)
    print(f"Saved: {filename} (shape: {data['NSGMAX']} x {data['NTGMAX']})")
    
    # 7. DELPSI mesh
    filename = f'{prefix}_DELPSI_mesh.csv'
    np.savetxt(filename, data['DELPSI'], delimiter=',',
               header=','.join([f'theta_{i}' for i in range(data['NTGMAX'])]),
               comments='')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    # 8. HJT mesh
    filename = f'{prefix}_HJT_mesh.csv'
    np.savetxt(filename, data['HJT'], delimiter=',',
               header=','.join([f'theta_{i}' for i in range(data['NTGMAX'])]),
               comments='')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    # 9. Radial profiles (NRVMAX)
    filename = f'{prefix}_radial_profiles.csv'
    nrv = data['NRVMAX']
    with open(filename, 'w') as f:
        f.write('index,PSIPNV,PSIPV,PSITV,QPV,TTV\n')
        for i in range(nrv):
            f.write(f'{i},{data["PSIPNV"][i]:.15e},{data["PSIPV"][i]:.15e},'
                   f'{data["PSITV"][i]:.15e},{data["QPV"][i]:.15e},{data["TTV"][i]:.15e}\n')
    output_files.append(filename)
    print(f"Saved: {filename} ({nrv} points)")
    
    # 10. HJTRZ 2D array
    filename = f'{prefix}_HJTRZ.csv'
    np.savetxt(filename, data['HJTRZ'], delimiter=',',
               header=','.join([f'Z_{i}' for i in range(data['NZGMAX'])]),
               comments='')
    output_files.append(filename)
    print(f"Saved: {filename}")
    
    return output_files


def main():
    """Main entry point."""
    # Parse arguments
    if len(sys.argv) >= 2:
        input_file = sys.argv[1]
    else:
        input_file = 'eqdata'
    
    if len(sys.argv) >= 3:
        output_prefix = sys.argv[2]
    else:
        output_prefix = os.path.splitext(input_file)[0]
    
    print(f"Reading binary file: {input_file}")
    print(f"Output prefix: {output_prefix}")
    print("-" * 60)
    
    # Check input file exists
    if not os.path.exists(input_file):
        print(f"Error: Input file '{input_file}' not found!")
        sys.exit(1)
    
    # Read binary data
    try:
        data = read_eqdata(input_file)
    except Exception as e:
        print(f"Error reading binary file: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    # Print summary
    print("\nData Summary:")
    print(f"  Major radius RR = {data['RR']:.4f} m")
    print(f"  Toroidal field BB = {data['BB']:.4f} T")
    print(f"  Plasma current RIP = {data['RIP']:.4e} A")
    print(f"  Grid: {data['NRGMAX']} x {data['NZGMAX']} (R x Z)")
    print(f"  Magnetic axis: ({data['RAXIS']:.4f}, {data['ZAXIS']:.4f}) m")
    print(f"  Minor radius RA = {data['RA']:.4f} m")
    print(f"  Elongation RKAP = {data['RKAP']:.4f}")
    print(f"  Triangularity RDLT = {data['RDLT']:.4f}")
    print("-" * 60)
    
    # Export to CSV
    output_files = export_to_csv(data, output_prefix)
    
    print("-" * 60)
    print(f"Successfully exported {len(output_files)} CSV files.")
    
    return data


if __name__ == '__main__':
    main()
