#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from solve_gs_from_gfile import read_gfile

PI = np.pi
TWOPI = 2.0 * np.pi


def _wrap_0_2pi(theta: np.ndarray) -> np.ndarray:
    t = np.mod(theta, TWOPI)
    t[t < 0.0] += TWOPI
    return t


def _merge_duplicate_theta(theta: np.ndarray, rho: np.ndarray, tol: float = 1e-8) -> tuple[np.ndarray, np.ndarray]:
    if theta.size == 0:
        return theta, rho
    th = [float(theta[0])]
    rh = [float(rho[0])]
    for i in range(1, theta.size):
        if float(theta[i] - th[-1]) > tol:
            th.append(float(theta[i]))
            rh.append(float(rho[i]))
        else:
            rh[-1] = 0.5 * (rh[-1] + float(rho[i]))
    return np.asarray(th, dtype=float), np.asarray(rh, dtype=float)


def _build_periodic_interp(theta_sorted: np.ndarray, rho_sorted: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    # EQSET_RHOB_FROM_RSU style periodic extension
    thp = np.empty(theta_sorted.size + 2, dtype=float)
    rhp = np.empty(rho_sorted.size + 2, dtype=float)
    thp[0] = theta_sorted[-1] - TWOPI
    rhp[0] = rho_sorted[-1]
    thp[1:-1] = theta_sorted
    rhp[1:-1] = rho_sorted
    thp[-1] = theta_sorted[0] + TWOPI
    rhp[-1] = rho_sorted[0]
    return thp, rhp


def _interp_piecewise(th_query: np.ndarray, thp: np.ndarray, rhp: np.ndarray) -> np.ndarray:
    tq = _wrap_0_2pi(np.asarray(th_query, dtype=float))
    out = np.empty_like(tq)
    for i, t in enumerate(tq):
        j = np.searchsorted(thp, t, side="right") - 1
        j = max(0, min(j, thp.size - 2))
        dt = thp[j + 1] - thp[j]
        if abs(dt) <= 1e-12:
            out[i] = np.nan
        else:
            w = (t - thp[j]) / dt
            out[i] = (1.0 - w) * rhp[j] + w * rhp[j + 1]
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare RSU/ZSU with EQDEFB RHOM boundary single-valuedization.")
    parser.add_argument("--gfile", default="g260206.20000_teq_0114", help="Path to gfile (relative to in/ by default).")
    parser.add_argument("--params-csv", default="../eqdata0114_parameters.csv", help="eqdata parameters csv for RR/NTGMAX.")
    parser.add_argument("--ntgmax", type=int, default=None, help="Override NTGMAX used for RHOM discretization.")
    parser.add_argument("--out-prefix", default="lcfs_single_valued_compare", help="Output prefix (under in/ if relative).")
    args = parser.parse_args()

    in_dir = Path(__file__).resolve().parent
    repo_dir = in_dir.parent

    gfile_path = Path(args.gfile)
    if not gfile_path.is_absolute():
        if (in_dir / gfile_path).exists():
            gfile_path = in_dir / gfile_path
        elif (repo_dir / gfile_path).exists():
            gfile_path = repo_dir / gfile_path
    gfile_path = gfile_path.resolve()

    params_path = Path(args.params_csv)
    if not params_path.is_absolute():
        if (in_dir / params_path).exists():
            params_path = in_dir / params_path
        elif (repo_dir / params_path).exists():
            params_path = repo_dir / params_path
    params_path = params_path.resolve()

    out_prefix = Path(args.out_prefix)
    if not out_prefix.is_absolute():
        out_prefix = in_dir / out_prefix
    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    g = read_gfile(str(gfile_path))
    rsu = np.asarray(g.rbbbs, dtype=float)
    zsu = np.asarray(g.zbbbs, dtype=float)

    p = pd.read_csv(params_path)
    pmap = dict(zip(p["Parameter"], p["Value"]))
    rr = float(pmap["RR"])
    ntgmax = int(args.ntgmax) if args.ntgmax is not None else int(float(pmap["NTGMAX"]))

    # EQDEFB+EQSET_RHOB_FROM_RSU geometry center in current solver path:
    r0 = rr
    z0 = 0.0

    dx = rsu - r0
    dz = zsu - z0
    rho = np.hypot(dx, dz)
    theta = _wrap_0_2pi(np.arctan2(dz, dx))

    mask = rho > 1e-8
    theta = theta[mask]
    rho = rho[mask]
    rsu_m = rsu[mask]
    zsu_m = zsu[mask]

    order = np.argsort(theta)
    theta_s = theta[order]
    rho_s = rho[order]
    theta_u, rho_u = _merge_duplicate_theta(theta_s, rho_s)
    thp, rhp = _build_periodic_interp(theta_u, rho_u)

    dtg = TWOPI / float(ntgmax)
    thgm = dtg * (np.arange(ntgmax, dtype=float) + 0.5)
    rhom = _interp_piecewise(thgm, thp, rhp)

    # Boundary points generated by EQDEFB RHOM mesh (sigma=1 boundary)
    r_eq = r0 + rhom * np.cos(thgm)
    z_eq = z0 + rhom * np.sin(thgm)

    # Rebuild rho(theta) from RHOM samples, then compare on original RSU angles
    thgm_ext = np.r_[thgm, thgm[0] + TWOPI]
    rhom_ext = np.r_[rhom, rhom[0]]
    rho_rec = _interp_piecewise(theta, thgm_ext, rhom_ext)
    r_rec = r0 + rho_rec * np.cos(theta)
    z_rec = z0 + rho_rec * np.sin(theta)

    drho = rho_rec - rho
    dR = r_rec - rsu_m
    dZ = z_rec - zsu_m
    dist = np.hypot(dR, dZ)

    i_max = int(np.nanargmax(np.abs(dist)))
    print("=== LCFS single-valuedization error (RSU/ZSU vs RHOM->(R,Z)) ===")
    print(f"gfile: {gfile_path}")
    print(f"params: {params_path}")
    print(f"RR={rr:.6f}, NTGMAX={ntgmax}, center=(R0,Z0)=({r0:.6f},{z0:.6f})")
    print(f"N_RSU={len(rsu_m)}, N_RHOM={len(rhom)}")
    print(f"mean(|dist|)={np.nanmean(np.abs(dist)):.6e} m")
    print(f"max(|dist|)={np.nanmax(np.abs(dist)):.6e} m at idx={i_max}")
    print(f"  RSU/ZSU=({rsu_m[i_max]:.6f},{zsu_m[i_max]:.6f})")
    print(f"  RHOMpt= ({r_rec[i_max]:.6f},{z_rec[i_max]:.6f})")
    print(f"  theta={theta[i_max]:.6f} rad, drho={drho[i_max]:.6e} m")

    df_rhom = pd.DataFrame(
        {
            "index": np.arange(1, ntgmax + 1),
            "THGM": thgm,
            "RHOM": rhom,
            "R_RHOM": r_eq,
            "Z_RHOM": z_eq,
        }
    )
    df_err = pd.DataFrame(
        {
            "index": np.arange(1, len(theta) + 1),
            "RSU": rsu_m,
            "ZSU": zsu_m,
            "theta": theta,
            "rho_orig": rho,
            "rho_recon": rho_rec,
            "drho": drho,
            "R_recon": r_rec,
            "Z_recon": z_rec,
            "dR": dR,
            "dZ": dZ,
            "dist": dist,
        }
    )

    rhom_csv = out_prefix.with_name(out_prefix.name + "_rhom_boundary.csv")
    err_csv = out_prefix.with_name(out_prefix.name + "_error_on_rsu.csv")
    df_rhom.to_csv(rhom_csv, index=False)
    df_err.to_csv(err_csv, index=False)

    fig, ax = plt.subplots(1, 2, figsize=(13, 5.5), constrained_layout=True)
    ax[0].plot(rsu_m, zsu_m, "b-", lw=1.8, label="RSU/ZSU (gfile LCFS)")
    ax[0].plot(r_eq, z_eq, "ro-", ms=3.0, lw=1.2, label="EQDEFB RHOM->(R,Z)")
    ax[0].plot([rsu_m[i_max]], [zsu_m[i_max]], "ks", ms=6, label="max error point")
    ax[0].set_xlabel("R (m)")
    ax[0].set_ylabel("Z (m)")
    ax[0].set_aspect("equal")
    ax[0].grid(alpha=0.3)
    ax[0].set_title("Boundary Overlay")
    ax[0].legend(fontsize=8)

    ax[1].plot(theta, dist, "k.", ms=3.0)
    ax[1].axhline(np.nanmean(np.abs(dist)), color="tab:orange", ls="--", lw=1.2, label="mean |dist|")
    ax[1].axhline(np.nanmax(np.abs(dist)), color="tab:red", ls="--", lw=1.2, label="max |dist|")
    ax[1].set_xlabel("theta (rad)")
    ax[1].set_ylabel("|delta r| (m)")
    ax[1].grid(alpha=0.3)
    ax[1].set_title("Single-valuedization Error on RSU points")
    ax[1].legend(fontsize=8)

    png = out_prefix.with_suffix(".png")
    fig.savefig(png, dpi=170)
    print(f"Saved: {rhom_csv}")
    print(f"Saved: {err_csv}")
    print(f"Saved: {png}")


if __name__ == "__main__":
    main()
