!     ***********************************************************

!           TIME EVOLUTIONAL UFILE DATA INPUT ROUTINE

!     ***********************************************************

      SUBROUTINE TR_TIME_UFILE

      USE TRCOMM, ONLY : &
           ABRHOU, AJNBU, AJU, AR1RHOU, AR1RHOU, AR2RHOU, AR2RHOU, ARRHOU, &
           BB, BBU, BPU, DR, DT, DVRHOU, KUFDCG, KUFDEV, MDLJQ, MDLXP, MDNI, &
           MDPHIA, NRAMAX, NRMAX, NRMP, NRUM, NSM, NTUM, PBMU, PECU, PHIA, &
           PHIAU, PICU, PN, PNBIU, PNBU, PNFU, PNFUA, PNFUA, PNS, PNSA, &
           PNSU, PNSUA, POHU, POHU, PRLU, PT, PTS, PTSA, PTSU, PTSUA, PZ, &
           QPU, RA, RAU, RHOA, RIPE, RIPS, RIPU, RKAP, RKAPU, RKPRHOU, &
           RKPRHOU, RMJRHOU, RMNRHOU, RMNRHOU, RNFU, RNU, RNU_ORG, RR, RRU, &
           RT, RTU, TTRHOU, VOLAU, WROTU, ZEFFU, ZEFFU_ORG, rkind
      USE TRCOM1, ONLY : KDIRX, NMCHK, NTAMAX, NTXMAX, NTXMAX1, TMU, TMU1
      IMPLICIT NONE
      INTEGER:: ICK, IERR, MDAMIN, MDBT, MDIP, MDKAPPA, MDPNBI, MDRGEO, NTAMAX1, NTX
      INTEGER:: MDCHK, MDSUM, NR, NRLMAX, NS
      REAL(rkind)   :: AMP, TMUMAX
      REAL(rkind),DIMENSION(NTUM)     :: PV, PV2, PV2A, PV3, PV3A, PVA, TL, ZEV, ZEVA
      REAL(rkind),DIMENSION(NRUM)     :: RL
      REAL(rkind),DIMENSION(NTUM,NRMP):: FAT
      REAL(rkind),DIMENSION(NTUM,NRUM):: F2
      CHARACTER(LEN=10):: KFID


      ICK=0
      TMUMAX=0.D0

      MDRGEO=0
      MDAMIN=0
      MDIP=0
      MDBT=0
      MDKAPPA=0
      MDPHIA=0
      MDPNBI=0

!     *** 1D VALUE ***

      KFID='RGEO'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,RRU ,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDRGEO=IERR
         IERR=0
      ENDIF

      KFID='AMIN'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,RAU ,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDAMIN=IERR
         IERR=0
      ENDIF

      KFID='IP'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,RIPU ,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDIP=IERR
         IERR=0
      ELSE
         RIPU(1:NTXMAX1)=ABS(RIPU(1:NTXMAX1)*1.D-6)
      ENDIF

      KFID='BT'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,BBU  ,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDBT=IERR
         IERR=0
      ELSE
         BBU(1:NTXMAX1)=ABS(BBU(1:NTXMAX1))
      ENDIF

      KFID='KAPPA'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,RKAPU,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDKAPPA=IERR
         IERR=0
      ENDIF
!$$$      IF(IERR.EQ.1) THEN
!$$$         RKAPU(1:NTXMAX1)=1.D0
!$$$      ENDIF

      KFID='PHIA'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,PHIAU,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDPHIA=IERR
         IERR=0
      ENDIF

      KFID='PNBI'
      CALL UF1D(KFID,KUFDEV,KUFDCG,DT,TMU1,PNBIU,NTAMAX1,NTXMAX1,TMUMAX,ICK,MDLXP,IERR)
      IF(IERR.EQ.1) THEN
         MDPNBI=IERR
         IERR=0
      ENDIF

      RR    = RRU(1)
      RA    = RAU(1)
      RIPS  = RIPU(1)
      RIPE  = RIPU(1)
      BB    = BBU(1)
      RKAP  = RKAPU(1)
      PHIA  = PHIAU(1)

!     *** 2D VALUE ***

      AMP=1.D-3
      KFID='TE'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV,PVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      RTU(1:NTXMAX,1:NRMAX,1)=FAT(1:NTXMAX,1:NRMAX)
      RT(1:NRMAX,1)=RTU(1,1:NRMAX,1)
      PT(1)=RT(1,1)
      PTSU(1:NTXMAX,1)=PV(1:NTXMAX)
      PTS(1)=PTSU(1,1)
      IF(RHOA.NE.1.D0) THEN
         PTSUA(1:NTXMAX,1)=PVA(1:NTXMAX)
         PTSA(1)=PTSUA(1,1)
      ENDIF

      KFID='TI'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV,PVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      DO NS=2,NSM
         RTU(1:NTXMAX,1:NRMAX,NS)=FAT(1:NTXMAX,1:NRMAX)
         RT(1:NRMAX,NS)=RTU(1,1:NRMAX,NS)
         PTSU(1:NTXMAX,NS)=PV(1:NTXMAX)
         PTS (NS)=PTSU(1,NS)
      ENDDO
      PT(2)=RT(1,2)
      PT(3)=RT(1,3)
      PT(4)=RT(1,2)
      IF(RHOA.NE.1.D0) THEN
         DO NS=2,NSM
            PTSUA(1:NTXMAX,NS)=PVA(1:NTXMAX)
            PTSA(NS)=PTSUA(1,NS)
         ENDDO
      ENDIF

      AMP=1.D-20
      KFID='NE'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV,PVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      RNU(1:NTXMAX,1:NRMAX,1)=FAT(1:NTXMAX,1:NRMAX)
      RNU(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
      RNU(1:NTXMAX,1:NRMAX,3)=1.D-7
      RNU(1:NTXMAX,1:NRMAX,4)=1.D-7
      RNU_ORG(1:NTXMAX,1:NRMAX,1)=FAT(1:NTXMAX,1:NRMAX)
      RNU_ORG(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
      ZEFFU(1:NTXMAX,1:NRMAX)=1.D0     ! in case of MDNI=0
      ZEFFU_ORG(1:NTXMAX,1:NRMAX)=1.D0 ! in case of MDNI=0
      PNSU(1:NTXMAX,1)=PV(1:NTXMAX)
      PNSU(1:NTXMAX,2)=PV(1:NTXMAX)
      PNSU(1:NTXMAX,3)=1.D-8
      PNSU(1:NTXMAX,4)=1.D-8
      PN(1)=RNU(1,1,1)
      PN(2)=RNU(1,1,2)
      PN(3)=1.D-7
      PN(4)=1.D-7
      PNS(1)=PNSU(1,1)
      PNS(2)=PNSU(1,2)
      PNS(3)=PNSU(1,3)
      PNS(4)=PNSU(1,4)
      IF(RHOA.NE.1.D0) THEN
         PNSUA(1:NTXMAX,1)=PVA(1:NTXMAX)
         PNSUA(1:NTXMAX,2)=PVA(1:NTXMAX)
         PNSUA(1:NTXMAX,3)=1.D-8
         PNSUA(1:NTXMAX,4)=1.D-8
         PNSA(1)=PNSUA(1,1)
         PNSA(2)=PNSUA(1,2)
         PNSA(3)=PNSUA(1,3)
         PNSA(4)=PNSUA(1,4)
      ENDIF

      KFID='NFAST'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PNFU,PNFUA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      DO NTX=1,NTXMAX
         DO NR=1,NRMAX
            IF(IERR.EQ.0.AND.FAT(NTX,NR).LE.0.D0) FAT(NTX,NR)=1.D-10
            RNFU(NTX,NR)=FAT(NTX,NR)
         ENDDO
      ENDDO

      KFID='NM1'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV,PVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      IF(NMCHK.EQ.0) THEN
         IF(MDNI.NE.0) THEN
            RNU(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
            IF(IERR.EQ.0) RNU_ORG(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
            RNU_ORG(1:NTXMAX,1:NRMAX,4)=0.D0
            PNSU(1:NTXMAX,2)=PV(1:NTXMAX)
            IF(RHOA.NE.1.D0) PNSUA(1:NTXMAX,2)=PVA(1:NTXMAX)
         ELSE
            IF(IERR.EQ.0) RNU_ORG(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
         ENDIF
      ELSE
         RNU_ORG(1:NTXMAX,1:NRMAX,4)=FAT(1:NTXMAX,1:NRMAX)
      ENDIF
      IF(NMCHK.GE.1) THEN
         KFID='NM2'
         CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV2,PV2A,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
         RNU_ORG(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)
         IF(MDNI.NE.0) THEN
            RNU(1:NTXMAX,1:NRMAX,2)=FAT(1:NTXMAX,1:NRMAX)+RNU_ORG(1:NTXMAX,1:NRMAX,4)
            PNSU(1:NTXMAX,2)=PV(1:NTXMAX)+PV2(1:NTXMAX)
            IF(RHOA.NE.1.D0) PNSUA(1:NTXMAX,2)=PVA(1:NTXMAX)+PV2A(1:NTXMAX)
         ENDIF
      ENDIF
      IF(NMCHK.GE.2) THEN
         KFID='NM3'
         CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV3,PV3A,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
         RNU_ORG(1:NTXMAX,1:NRMAX,4)=RNU_ORG(1:NTXMAX,1:NRMAX,4)+FAT(1:NTXMAX,1:NRMAX)
         IF(MDNI.NE.0) THEN
            RNU(1:NTXMAX,1:NRMAX,2)=RNU(1:NTXMAX,1:NRMAX,2)+FAT(1:NTXMAX,1:NRMAX)
            PNSU(1:NTXMAX,2)=PNSU(1:NTXMAX,2)+PV3(1:NTXMAX)
            IF(RHOA.NE.1.D0) PNSUA(1:NTXMAX,2)=PNSUA(1:NTXMAX,2)+PV3A(1:NTXMAX)
         ENDIF
      ENDIF

      AMP=1.D0
      KFID='ZEFFR'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,ZEV,ZEVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      IF(MDNI.NE.0) ZEFFU(1:NTXMAX,1:NRMAX)=FAT(1:NTXMAX,1:NRMAX)
      ZEFFU_ORG(1:NTXMAX,1:NRMAX)=FAT(1:NTXMAX,1:NRMAX)

      AMP=1.D-20
      KFID='NIMP'
      CALL UF2DTP(KFID,KUFDEV,KUFDCG,DR,DT,PV,PVA,TMU,FAT,AMP, &
     &          NTAMAX,NTXMAX,RHOA,NRAMAX,NRMAX,TMUMAX,0,ICK,MDLXP,IERR)
      IF(MDNI.NE.0) THEN
         RNU(1:NTXMAX,1:NRMAX,3)=FAT(1:NTXMAX,1:NRMAX)
         RNU_ORG(1:NTXMAX,1:NRMAX,3)=FAT(1:NTXMAX,1:NRMAX)
         PNSU(1:NTXMAX,3)=PV(1:NTXMAX)
         IF(RHOA.NE.1.D0) PNSUA(1:NTXMAX,3)=PVA(1:NTXMAX)
      ELSE
         RNU_ORG(1:NTXMAX,1:NRMAX,3)=FAT(1:NTXMAX,1:NRMAX)
      ENDIF

      select case(MDNI)
      case(1)

      DO NTX=1,NTXMAX
         DO NR=1,NRMAX
            RNU(NTX,NR,2)=( (PZ(3)-ZEFFU(NTX,NR))*RNU(NTX,NR,1)-(PZ(3)-PZ(2))*PZ(2)*RNFU(NTX,NR))/(PZ(2)*(PZ(3)-PZ(2)))
            RNU(NTX,NR,3)=(PZ(2)-ZEFFU(NTX,NR))/(PZ(3)*(PZ(2)-PZ(3)))*RNU(NTX,NR,1)
         ENDDO
         PNSU(NTX,2)=( (PZ(3)-ZEV(NTX))*PNSU(NTX,1)-(PZ(3)-PZ(2))*PZ(2)*PNFU(NTX))/(PZ(2)*(PZ(3)-PZ(2)))
         PNSU(NTX,3)=(PZ(2)-ZEV(NTX))/(PZ(3)*(PZ(2)-PZ(3)))*PNSU(NTX,1)
         PNSU(NTX,4)=1.D-8
      ENDDO
      PN(2)=RNU(1,1,2)
      PN(3)=RNU(1,1,3)
      PN(4)=1.D-7
      PNS(2)=PNSU(1,2)
      PNS(3)=PNSU(1,3)
      PNS(4)=PNSU(1,4)
      IF(RHOA.NE.1.D0) THEN
         DO NTX=1,NTXMAX
            PNSUA(NTX,2)=( (PZ(3)-ZEVA(NTX))*PNSUA(NTX,1)-(PZ(3)-PZ(2))*PZ(2)*PNFUA(NTX))/(PZ(2)*(PZ(3)-PZ(2)))
            PNSUA(NTX,3)=(PZ(2)-ZEVA(NTX))/(PZ(3)*(PZ(2)-PZ(3)))*PNSUA(NTX,1)
            PNSUA(NTX,4)=1.D-8
         ENDDO
         PNSA(2)=PNSUA(1,2)
         PNSA(3)=PNSUA(1,3)
         PNSA(4)=PNSUA(1,4)
      ENDIF

      case(2)

      DO NTX=1,NTXMAX
         DO NR=1,NRMAX
            RNU(NTX,NR,3)=(RNU(NTX,NR,1)-(RNU(NTX,NR,2)+RNFU(NTX,NR))* PZ(2))/PZ(3)
            ZEFFU(NTX,NR)=PZ(2)*(PZ(2)-PZ(3))*(RNU(NTX,NR,2)+RNFU(NTX,NR))/ RNU(NTX,NR,1)+PZ(3)
         ENDDO
         PNSU(NTX,3)=(PNSU(NTX,1)-(PNSU(NTX,2)+PNFU(NTX))*PZ(2))/PZ(3)
         PNSU(NTX,4)=1.D-8
      ENDDO
      PN(2)=RNU(1,1,2)
      PN(3)=RNU(1,1,3)
      PN(4)=1.D-7
      PNS(2)=PNSU(1,2)
      PNS(3)=PNSU(1,3)
      PNS(4)=PNSU(1,4)
      IF(RHOA.NE.1.D0) THEN
         DO NTX=1,NTXMAX
            PNSUA(NTX,3)=(PNSUA(NTX,1)-(PNSUA(NTX,2)+PNFUA(NTX))*PZ(2))/PZ(3)
            PNSUA(NTX,4)=1.D-8
         ENDDO
         PNSA(2)=PNSUA(1,2)
         PNSA(3)=PNSUA(1,3)
         PNSA(4)=PNSUA(1,4)
      ENDIF

      case(3)

      DO NTX=1,NTXMAX
         DO NR=1,NRMAX
            RNU(NTX,NR,2)=( RNU(NTX,NR,1)-PZ(2)*RNFU(NTX,NR)-PZ(3)*RNU(NTX,NR,3))/PZ(2)
            ZEFFU(NTX,NR)=PZ(2)+PZ(3)*(PZ(3)-PZ(2))*(RNU(NTX,NR,3)/RNU(NTX,NR,1))
         ENDDO
         PNSU(NTX,2)=(PNSU(NTX,1)-PZ(2)*PNFU(NTX) -PZ(3)*PNSU(NTX,3))/PZ(2)
         PNSU(NTX,4)=1.D-8
      ENDDO
      PN(2)=RNU(1,1,2)
      PN(3)=RNU(1,1,3)
      PN(4)=1.D-7
      PNS(2)=PNSU(1,2)
      PNS(3)=PNSU(1,3)
      PNS(4)=PNSU(1,4)
      IF(RHOA.NE.1.D0) THEN
         DO NTX=1,NTXMAX
            PNSUA(NTX,2)=(PNSUA(NTX,1)-PZ(2)*PNFUA(NTX) -PZ(3)*PNSUA(NTX,3))/PZ(2)
            PNSUA(NTX,4)=1.D-8
         ENDDO
         PNSA(2)=PNSUA(1,2)
         PNSA(3)=PNSUA(1,3)
         PNSA(4)=PNSUA(1,4)
      ENDIF
      end select

!     check whether density developed is appropriate (positive) or not
      IF(MDNI.NE.0) THEN
      DO NTX=1,NTXMAX
         DO NR=1,NRMAX
            IF(RNU(NTX,NR,2).LE.0.D0.OR.RNU(NTX,NR,3).LE.0.D0) THEN
               WRITE(6,*) 'XX TR_STEADY_UFILE: DENSITY NEGATIVE: WRONG MDNI=',MDNI
               STOP
            ENDIF
         ENDDO
      ENDDO
      ENDIF

      AMP=1.D0
      KFID='PBEAM'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,PBMU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      KFID='Q'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,QPU ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,1,1,ICK,MDLXP,IERR)
      IF(IERR.NE.0.AND.MDLJQ.EQ.1) MDLJQ=0
      KFID='CURTOT'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,AJU ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      IF(IERR.NE.0.AND.MDLJQ.EQ.0) MDLJQ=1
      KFID='CURNBI'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,AJNBU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      KFID='BPOL'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,BPU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,1,0,ICK,MDLXP,IERR)
      KFID='QNBIE'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      forall(NTX=1:NTXMAX,NR=1:NRMAX,FAT(NTX,NR) < 0.D0) FAT(NTX,NR) = 0.D0
      PNBU(1:NTXMAX,1:NRMAX,1) = FAT(1:NTXMAX,1:NRMAX)

      KFID='QNBII'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      forall(NTX=1:NTXMAX,NR=1:NRMAX,FAT(NTX,NR) < 0.D0) FAT(NTX,NR) = 0.D0
      PNBU(1:NTXMAX,1:NRMAX,2) = FAT(1:NTXMAX,1:NRMAX)

      PICU(1:NTXMAX,1:NRMAX,1)=0.D0
      PICU(1:NTXMAX,1:NRMAX,2)=0.D0
      PECU(1:NTXMAX,1:NRMAX  )=0.D0
      POHU(1:NTXMAX,1:NRMAX  )=0.D0
      KFID='QICRHE'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      forall(NTX=1:NTXMAX,NR=1:NRMAX,FAT(NTX,NR) < 0.D0) FAT(NTX,NR) = 0.D0
      PICU(1:NTXMAX,1:NRMAX,1) = FAT(1:NTXMAX,1:NRMAX)

      KFID='QICRHI'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      forall(NTX=1:NTXMAX,NR=1:NRMAX,FAT(NTX,NR) < 0.D0) FAT(NTX,NR) = 0.D0
      PICU(1:NTXMAX,1:NRMAX,2) = FAT(1:NTXMAX,1:NRMAX)

      KFID='QECH'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT ,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      forall(NTX=1:NTXMAX,NR=1:NRMAX,FAT(NTX,NR) < 0.D0) FAT(NTX,NR) = 0.D0
      PECU(1:NTXMAX,1:NRMAX) = FAT(1:NTXMAX,1:NRMAX)

      KFID='QRAD'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,PRLU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)

      KFID='QOHM'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,POHU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)

      KFID='VROT'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,WROTU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,1,1,ICK,MDLXP,IERR)

!     *****

      MDSUM=MDRGEO+MDAMIN+MDIP+MDBT+MDKAPPA+MDPHIA+MDPNBI
      IF(MDSUM.NE.0) THEN
         NTXMAX1=NTXMAX
         IF(MDRGEO .NE.0) RRU  (1:NTXMAX1)=RR
         IF(MDAMIN .NE.0) RAU  (1:NTXMAX1)=RA
         IF(MDIP   .NE.0) RIPU (1:NTXMAX1)=RIPS
         IF(MDBT   .NE.0) BBU  (1:NTXMAX1)=BB
         IF(MDKAPPA.NE.0) RKAPU(1:NTXMAX1)=RKAP
         IF(MDPHIA .NE.0) PHIAU(1:NTXMAX1)=0.D0
         IF(MDPNBI .NE.0) PNBIU(1:NTXMAX1)=0.D0
         TMU1(1:NTXMAX1)=TMU(1:NTXMAX1)
      ENDIF

!     *** GEOMETRY FACTORS ***

      KFID='RMAJOR'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,RMJRHOU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,1,1,ICK,MDLXP,IERR)
      DO NR=1,NRMAX
         ARRHOU(1:NTXMAX,NR)=1.D0/RRU(1:NTXMAX)**2
         TTRHOU(1:NTXMAX,NR)=RRU(1:NTXMAX)*BBU(1:NTXMAX)
      ENDDO
      IF(MDRGEO.NE.0) RRU(1:NTXMAX)=RMJRHOU(1:NTXMAX,1)

      KFID='RMINOR'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,RMNRHOU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,1,0,ICK,MDLXP,IERR)
      IF(MDAMIN.NE.0) RAU(1:NTXMAX)=RMNRHOU(1:NTXMAX,NRMAX)

      KFID='KAPPAR'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,RKPRHOU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      IF(MDKAPPA.NE.0) RKAPU(1:NTXMAX)=RKPRHOU(1:NTXMAX,NRMAX)

      KFID='GRHO1'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,AR1RHOU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)

      KFID='GRHO2'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,AR2RHOU,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,1,ICK,MDLXP,IERR)
      ABRHOU(1:NTXMAX,1:NRMAX)=AR2RHOU(1:NTXMAX,1:NRMAX)*ARRHOU(1:NTXMAX,1:NRMAX)

      KFID='SURF'
      CALL UF2DT(KFID,KUFDEV,KUFDCG,DR,DT,TMU,FAT,AMP,NTAMAX,NTXMAX,NRMAX,TMUMAX,0,0,ICK,MDLXP,IERR)
      DVRHOU(1:NTXMAX,1:NRMAX)=FAT(1:NTXMAX,1:NRMAX)/AR1RHOU(1:NTXMAX,1:NRMAX)

      KFID='VOLUME'
      CALL UFREAD2_TIME(KDIRX,KUFDEV,KUFDCG,KFID,RL,TL,F2,NRLMAX,NTXMAX,NRUM,NTUM,MDCHK,IERR)
      VOLAU(1:NTXMAX)=F2(1:NTXMAX,NRLMAX)

      IF(NTAMAX.LT.NTAMAX1) NTAMAX=NTAMAX1
      RETURN
      END SUBROUTINE TR_TIME_UFILE
