MODULE TRCOM0

  USE bpsd_kinds,ONLY: rkind
  IMPLICIT NONE

! TRCOM0
  INTEGER  :: NEQMAXM, NVM, MWM, MLM, NRMP, NGLF, LDAB
  INTEGER  :: NRMAX, NSMAX, NSZMAX, NSNMAX
  INTEGER  :: NRMAX_OLD=0, NSMAX_OLD=0, NSZMAX_OLD=0, NSNMAX_OLD=0
  INTEGER, PARAMETER :: NSMM=100 ! Max number of species for namelist input
  INTEGER, PARAMETER :: NSM=4, NSZM=2, NSNM=2
  INTEGER, PARAMETER :: NTM =10001, NGM=1001, NFM=2
  INTEGER, PARAMETER :: NCGM=23, NCTM=110, NCRTM=67, NSTM=8
  INTEGER, PARAMETER :: NEQM=3*NSTM+1
  INTEGER, PARAMETER :: NLM =1001
  INTEGER, PARAMETER :: NTUM=1001, NRUM=102   ! Size of ufile data

END MODULE TRCOM0
